Improve triage notification further
Hopefully, doing all the checks in the shell script makes this work better.

diff --git a/.github/workflows/notify-triage.yml b/.github/workflows/notify-triage.yml
--- a/.github/workflows/notify-triage.yml
+++ b/.github/workflows/notify-triage.yml
@@ -7,17 +7,32 @@ jobs:
   notify:
     runs-on: ubuntu-latest
     steps:
-    - name: Reject invalid event type
-      if: ${{ github.event_name != "issue" && github.event_name != "pull_request_target" }}
-      run: |
-        echo "::error::This action must only be run on 'issue' and 'pull_request_target' events"
-        exit 1
-    - name: Notify triage
-      if: ${{ github.event_name == "issue" || github.event_name == "pull_request_target" }}
-      run: |
-        export GITHUB_TOKEN="$GH_TOKEN_SECRET"
-        gh issue edit "$ISSUE_URL" --add-project 'Triage/bugs' &&
-        gh issue comment "$ISSUE_URL" --body '@MithrilJS/triage Please take a look.'
+    - name: Run workflow
       env:
-        ISSUE_URL: ${{ github.event.issue.url || github.event.pull_request.url }}
         GH_TOKEN_SECRET: ${{ github.token }}
+      run: |
+        set -euo pipefail
+
+        echo "event name: $GITHUB_EVENT_NAME"
+
+        case "$GITHUB_EVENT_NAME" in
+          "issue")
+            cmd=issue
+            url="$(jq -r .issue.url <"$GITHUB_EVENT_PATH")"
+            ;;
+          "pull_request_target")
+            cmd=pr
+            url="$(jq -r .pull_request.url <"$GITHUB_EVENT_PATH")"
+            ;;
+          *)
+            echo "::error::This action must only be run on 'issue' and 'pull_request_target' events"
+            exit 1
+            ;;
+        esac
+
+        echo "cmd: $cmd"
+        echo "url: $url"
+
+        export GITHUB_TOKEN="$GH_TOKEN_SECRET"
+        gh $cmd edit "$url" --add-project 'Triage/bugs' &&
+        gh $cmd comment "$url" --body '@MithrilJS/triage Please take a look.'
